// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using ChuiWenChiu.Utility;
namespace TestProject2 {
    /// <summary>
    ///This is a test class for ChuiWenChiu.Utility.CWMProject and is intended
    ///to contain all ChuiWenChiu.Utility.CWMProject Unit Tests
    ///</summary>
    [TestClass()]
    public class CWMProjectTest {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext {
            get {
                return testContextInstance;
            }
            set {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for CWMProject ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest() {
            CWMProject target = new CWMProject();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for CWMProject (string, string)
        ///</summary>
        [TestMethod()]
        public void ConstructorTest1() {
            string name = null; // TODO: Initialize to an appropriate value

            string tag = null; // TODO: Initialize to an appropriate value

            CWMProject target = new CWMProject(name, tag);

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for name
        ///</summary>
        [TestMethod()]
        public void nameTest() {
            CWMProject target = new CWMProject();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.name = val;


            Assert.AreEqual(val, target.name, "ChuiWenChiu.Utility.CWMProject.name was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for tag
        ///</summary>
        [TestMethod()]
        public void tagTest() {
            CWMProject target = new CWMProject();

            string val = null; // TODO: Assign to an appropriate value for the property

            target.tag = val;


            Assert.AreEqual(val, target.tag, "ChuiWenChiu.Utility.CWMProject.tag was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
